name: Copy frontend content to S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: 